[tasks.build-aarch64]
command = "cross"
args = ["build", "--release", "--target", "aarch64-unknown-linux-gnu"]

[tasks.upload-vps]
dependencies = ["build-aarch64"]
script = '''
scp target/aarch64-unknown-linux-gnu/release/the-devs-bot shaybox@vps:/home/shaybox/.cargo/bin/the-devs-bot
'''